services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel-11

    webserver:
        image: nginx:alpine
        restart: always
        ports:
            - "9090:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-11

    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        ports:
            - "3307:3307"
        networks:
            - laravel-11

    # queue:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     restart: always
    #     command: "php artisan queue:work"
    #     volumes:
    #         - ./:/var/www
    #     depends_on:
    #         # - redis
    #         - app
    #     networks:
    #         - laravel-11

    # redis:
    #     image: redis:latest
    #     networks:
    #         - laravel-11

networks:
    laravel-11:
        driver: bridge
